create table COUNTRY (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(4000)
    );

create table HOST
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references COUNTRY
);

create table STAY_USER
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table STAY
(
    id          bigint generated by default as identity primary key,
    name        varchar(255),
    category    varchar(255),
    host_id     bigint references HOST,
    numRooms    integer,
    isAvailable boolean default true
);

create table RESERVATION
(
    id            bigint generated by default as identity primary key,
    user_username varchar(255) references STAY_USER,
    stay_id       bigint references STAY,
    checkIn       timestamp,
    checkOut      timestamp,
    confirmed     boolean default false

);
