# apiVersion: v1
# kind: PersistentVolume
# metadata:
#  name: postgres-pv-2
# spec:
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  hostPath:
#    path: /data/postgres2
#    type: DirectoryOrCreate
