apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: hotel-app
data:
  init-replication.sql: |
    CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'replicator_password';